### ISSUE TITLE
Create a way to specify the app to run against

### ISSUE THREAD

**Issue by panozzaj** [catalyzeio/cli#22]
In our Catalyze environment(s), we have multiple apps. However, some of the commands don't appear to have a way to specify which app to run against.

Example 1: if we want to set the configuration variables for an app, it always seems to default to `app01` and there no way to configure this. So we have to go through the web interface. This works, but is suboptimal because the web interface is a little harder to work with.

Example 2: I don't see a way to run `rake` tasks against a certain app in the environment. https://resources.catalyze.io/paas/paas-cli-reference/rake/ says that you can run `catalyze rake db:migrate`, but it's not clear how to specify which server to run this against. In this case, we have multiple apps with different rake tasks, so specifying the application is important.

Does this make sense? Happy to try to explain in more detail.

**Comment by panozzaj** [comment]
You can associate to a specific service by specifying it when you run the 'associate' command: catalyze associate environment_name service_name

From there the service-less commands should default to using that service.

**Comment by chellberg** [comment]
Chiming in, if I'm understanding correctly the above wouldn't be a very good solution, since it would mean you'd need to reassociate to change ENV vars on multiple services on the same environment.

**Comment by jault3** [comment]
Currently you do have to associate N times where N is the number of services you have in your environment. In a future release we do plan on cleaning up these commands that don't allow specifying a service to run against. But for now I recommend the following: 

If you have an environment with two services, `app01` and `app02`, then run
```
cd /app01/git/repo
catalyze associate MyEnv app01 -a app01
cd /app02/git/repo
catalyze associate MyEnv app02 -a app02
```
Keep those associations around so that you can run commands such as 
```
catalyze -E app01 vars list
```
to list all app01 environment variables. Or
```
catalyze -E app02 vars list
```
to list all app02 environment variables. You wouldn't need to always reassociate, just N times upon initial setup. 

Thanks for the feature request and I will update this issue once it makes its way into a release! Much appreciated.
